# 1. Đường dẫn kết nối (Thay localhost, cổng 1433 và tên database của bạn)
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=MusicPlayerDB;encrypt=true;trustServerCertificate=true

# 2. Tài khoản & Mật khẩu SQL Server
spring.datasource.username=sa
spring.datasource.password=sapassword

# 3. Driver class
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# 4. Hibernate - Tự động tạo/cập nhật bảng dựa trên class Java
# 'update': Tự tạo bảng nếu chưa có, hoặc cập nhật nếu có thay đổi (Khuyên dùng khi mới học)
spring.jpa.hibernate.ddl-auto=update

# 5. Hiển thị câu lệnh SQL ra màn hình Console để dễ debug
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

app.jwt.secret=phanhoaibao020209kehfsh83847387374837!@^fTFTF@T@@T@F@
app.jwt.expiration=86400000